language: objective-c
osx_image: xcode8
env:
  global:
  - WORKSPACE=BrickKit.xcworkspace
  - IOS_SDK=iphonesimulator10.0
  - TVOS_SDK=appletvsimulator10.0
  - IOS_EXAMPLE_SCHEME="BrickApp-iOS"
  - TVOS_EXAMPLE_SCHEME="BrickApp-tvOS"
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 5"           SDK="$IOS_SDK"    EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SDK="$IOS_SDK"    EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"

    - DESTINATION="OS=9.0,name=Apple TV 1080p"     SDK="$TVOS_SDK"   EXAMPLE_SCHEME="$TVOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"    SDK="$TVOS_SDK"   EXAMPLE_SCHEME="$TVOS_EXAMPLE_SCHEME"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme BrickKit -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

  # Build Example in Debug
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BrickKit'
